### ISSUE TITLE
Remove all "cltk" imports from this repo

### ISSUE THREAD

**Issue by kylepjohnson** [cltk/cltkv1#77]
and change them to what our "new" namespace (`cltkv1`)

https://github.com/cltk/cltkv1/search?q=%22from+cltk.%22&unscoped_q=%22from+cltk.%22

In many cases, the code has been refactored and in others dropped entirely in this new repo.

(Note: Once the old package is entirely removed, we will do a complete find-replace for cltkv1 -> cltk)

**Comment by kylepjohnson** [comment]
A few notes:

- The first place to check is to replace module containing `from cltk.tokenize.` with from `cltkv1.tokenize.`
- If there is a commented-out unit test module (in `tests/`) which points to `cltk`, don't worry about it
- If an in-use unit test relies on a `from cltk` import, then try to update this. If you have any questions about where I moved the code our new package, just ask.

To test locally:
- Re-run the unit tests with `make testOnlyTestsDir` Note that three modules are really slow (test_main.py, test_embeddings.py, test_dependency.py) so you can point to particular test modules with  `poetry run pytest --disable-warnings tests/test_` (<---- module name here)
- The doctests now run in under 5 min, so these are good for local testing, too: `make testOnlyDocTests`






; note that the tests

**Comment by free-variation** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [https://github.com/cltk/cltkv1/issues/77](https://trello.com/c/0MGLgY7m/3-https-githubcom-cltk-cltkv1-issues-77)

**Comment by kylepjohnson** [comment]
^ This trello link is private

**Comment by free-variation** [comment]
> 
> ^ This trello link is private

Yeah, please ignore.  It's my personal CLTK board.

**Comment by free-variation** [comment]
@kylepjohnson @clemsciences

There are multiple language-specific syllabifiers strewn about: some under `stem`, some under `prosody` ... 

I noticed this because in removing cltk imports, there are syllabifiers from V0 under cltk.corpus that haven't made it to cltkv1.

I propose consolidating all syllabifiers under `phonology`.  While a debate about the boundary between phonology and prosody might be a little sterile, it looks as if in practice the prosody packages are concerned with e.g. meter.

**Comment by kylepjohnson** [comment]
This was perfect, no more imports. closing 🎆
